version: 2.1

orbs:
  win: circleci/windows@5.0
  
executors:
  linux:
    docker:
      - image: cimg/base:stable

jobs:
  build-linux:
    executor: linux
    steps:
      - run:
          name: Authenticate with GitHub
          command: |
            git config --global url."https://${GITHUB_TOKEN}@github.com/".insteadOf "git@github.com:"
            git clone https://github.com/emeiri/ogldev.git
      - run:
          name: Run Linux Build Script
          command: |
            cd ogldev
            chmod +x ./build_all.sh            
            ./build_all.sh

  build-windows:
    executor: win/default
    steps:
      - run:
          name: Authenticate with GitHub
          command: |
            git config --global url."https://${GITHUB_TOKEN}@github.com/".insteadOf "git@github.com:"
            git clone https://github.com/emeiri/ogldev.git
      - run:
          name: Build Solution
          command: |
            cd ogldev
            MSBuild "Windows\\ogldev_vs_2022\\ogldev_vs_2022.sln" /p:Configuration=Debug

workflows:
  version: 2
  build_all_platforms:
    jobs:
      - build-linux
      - build-windows
     