version: 2.1

orbs:
  win: circleci/windows@5.0
  
executors:
  linux:
    docker:
      - image: cimg/base:stable

jobs:
  build-linux:
    executor: linux
    steps:
      - checkout
      - run:
          name: Authenticate with GitHub
          command: |
            git config --global url."https://${GITHUB_TOKEN}@github.com/".insteadOf "git@github.com:"
      - run:
          name: Run Linux Build Script
          command: |
            chmod +x ./build_all.sh
            ./build_all.sh

  build-windows:
    executor:
      name: win/server-2022
      version: "current"
      size: medium
    steps:
      - checkout    
      - run:
          name: Authenticate with GitHub
          command: |
            git config --global url."https://${GITHUB_TOKEN}@github.com/".insteadOf "git@github.com:"

      - run:
          name: Build Solution
          command: >
            & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe" "Windows\\ogldev_vs_2022\\ogldev_vs_2022.sln" /p:Configuration=Release

workflows:
  version: 2
  build_all_platforms:
    jobs:
      - build-linux
      - build-windows
     