version: 2.1

orbs:
  win: circleci/windows@5.0
  
executors:
  ubuntu-executor:
    docker:
      - image: ubuntu:22.04

jobs:
  build-linux:
    executor: ubuntu-executor
    steps:
      - run:
          name: Install OpenGL and GLFW
          command: |
            sudo apt-get update
            sudo apt-get install -y freeglut3 freeglut3-dev libglew-dev libmagick++-dev libassimp-dev libglfw3 libglfw3-dev vulkan-tools vulkan-validationlayers vulkan-validationlayers-dev glslang-dev glslang-tools
      - run:
          name: Authenticate with GitHub
          command: |
            git config --global url."https://${GITHUB_TOKEN}@github.com/".insteadOf "git@github.com:"
            git clone --recurse-submodules https://github.com/emeiri/ogldev.git
      - run:
          name: Run Linux Build Script
          command: |
            cd ogldev
            chmod +x ./build_all.sh            
            ./build_all.sh

  build-windows:
    executor: win/default
    steps:
      - run:
          name: Download Vulkan SDK Installer
          command: |
            cmd /c curl -L -o VulkanSDK.exe https://sdk.lunarg.com/sdk/download/1.4.304.0/windows/VulkanSDK-1.4.304.0-Installer.exe
      - run:
          name: Install Vulkan SDK
          command: |
            Start-Process -FilePath .\VulkanSDK.exe -ArgumentList "--root C:\VulkanSDK\1.4.304.0 --accept-licenses --default-answer --confirm-command install com.lunarg.vulkan.debug" -Wait
      - run:
          name: Set Environment Variables
          command: |
            $env:VULKAN_SDK="C:\VulkanSDK\1.4.304.0\"
            $env:PATH="$env:VULKAN_SDK\Bin;$env:PATH"
      - run:
          name: Authenticate with GitHub
          command: |
            git config --global url."https://${GITHUB_TOKEN}@github.com/".insteadOf "git@github.com:"
            git clone --recurse-submodules https://github.com/emeiri/ogldev.git
      - run:
          name: Build Solution
          command: |
            cd ogldev
            cmd /c echo %VULKAN_SDK%
            cmd /c dir C:\VulkanSDK\1.4.304.0\Lib
            MSBuild "Windows\\ogldev_vs_2022\\ogldev_vs_2022.sln" /p:Configuration=Debug /m

workflows:
  version: 2
  build_all_platforms:
    jobs:
      - build-linux
      - build-windows
     