#ifndef TEXTURE_CONFIG_H
#define TEXTURE_CONFIG_H

#define COLOR_TEXTURE_UNIT_0 GL_TEXTURE0
#define COLOR_TEXTURE_UNIT_INDEX_0 0
#define COLOR_TEXTURE_UNIT_1 GL_TEXTURE1
#define COLOR_TEXTURE_UNIT_INDEX_1 1
#define COLOR_TEXTURE_UNIT_2 GL_TEXTURE2
#define COLOR_TEXTURE_UNIT_INDEX_2 2
#define COLOR_TEXTURE_UNIT_3 GL_TEXTURE3
#define COLOR_TEXTURE_UNIT_INDEX_3 3


#endif
