#ifndef TEXTURE_CONFIG_H
#define TEXTURE_CONFIG_H

// Terrain shader
#define COLOR_TEXTURE_UNIT_0       GL_TEXTURE0
#define COLOR_TEXTURE_UNIT_INDEX_0 0
#define COLOR_TEXTURE_UNIT_1       GL_TEXTURE1
#define COLOR_TEXTURE_UNIT_INDEX_1 1
#define COLOR_TEXTURE_UNIT_2       GL_TEXTURE2
#define COLOR_TEXTURE_UNIT_INDEX_2 2
#define COLOR_TEXTURE_UNIT_3       GL_TEXTURE3
#define COLOR_TEXTURE_UNIT_INDEX_3 3

// Water shader
#define REFLECTION_TEXTURE_UNIT       GL_TEXTURE4
#define REFLECTION_TEXTURE_UNIT_INDEX 4
#define REFRACTION_TEXTURE_UNIT       GL_TEXTURE5
#define REFRACTION_TEXTURE_UNIT_INDEX 5
#define DUDV_TEXTURE_UNIT             GL_TEXTURE6
#define DUDV_TEXTURE_UNIT_INDEX       6
#define NORMAL_MAP_TEXTURE_UNIT       GL_TEXTURE7
#define NORMAL_MAP_TEXTURE_UNIT_INDEX 7
#define DEPTH_MAP_TEXTURE_UNIT        GL_TEXTURE8
#define DEPTH_MAP_TEXTURE_UNIT_INDEX  8

#define SKYDOME_TEXTURE_UNIT          GL_TEXTURE9
#define SKYDOME_TEXTURE_UNIT_INDEX    9



#endif
