/*
		Copyright 2026 Etay Meiri

	This program is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/


#version 460

layout (local_size_x = 16, local_size_y = 16) in;
layout (binding = 0, rgba8) uniform image2D screenImage;

void main() 
{
    ivec2 uv = ivec2(gl_GlobalInvocationID.xy);
    ivec2 Size = imageSize(screenImage);
    
    if (uv.x >= Size.x || uv.y >= Size.y) {
		return;
	}

    vec3 Color = imageLoad(screenImage, uv).rgb;

    float GrayScale = dot(Color, vec3(0.2126, 0.7152, 0.0722));

	vec3 GrayColor = vec3(GrayScale);

    imageStore(screenImage, uv, vec4(GrayColor, 1.0));
}


